### ISSUE TITLE
Bug:  Returning undefined when used with Lambda in Node.js 10.x

### ISSUE THREAD

**Issue by poe9695** [VikramTiwari/reverse-geocode#22]
Using the latest version, 1.3.1, fails whenever i try to run it in a Lambda using Node.js 10.x

**Comment by poe9695** [comment]
Please return errors so I can debug it

**Comment by VikramTiwari** [comment]
Hey @poe9695 I just did a new release which should have fixed this. Could you please confirm? If not, could you please add some relevant logs of what your input to the function are. Thanks!

**Comment by poe9695** [comment]
Thanks, you fixed the issue.  It was just that AWS didn't treat "us" the same as "US", so wasn't able to find the file.  Was confusing since the README showed using "us", lowercase versions. 
Thanks for the fix!

**Comment by VikramTiwari** [comment]
Totally understand! Thanks for opening the issue.
